import '../models/project_model.dart';

final projects = [
  ProjectModel(
    title: "myUTS",
    description: [
      "myUTS is a vehicle tracking and fleet management application designed for real-time monitoring and operational visibility.",
      "The app allows users to track all registered vehicles with live location updates, alerts, and notifications.",
      "Users can view detailed vehicle information through a 360-degree overview that includes status, activity, and trip data.",
      "Trip history is visualized using paths and polygons, making it easy to analyze routes and movement patterns.",
      "The application provides analytics through graphs and reports to help users understand usage and performance trends.",
      "Additional modules include vehicle management, driver management, user activity logs, and customer care configuration.",
      "The app also features an executive mode where executives can view sales data filtered by custom date ranges.",
      "For improved user experience, incoming notifications are announced using voice alerts.",
      "The project was an existing production app, and my role focused on maintenance, stability improvements, and architectural upgrades.",
    ],
    technologies: ["Flutter", "GetX", "Provider", "Riverpod", "Firebase", "Google Maps", "REST APIs"],
    achievements: [
      "Reduced application crashes by approximately 80% by identifying and fixing critical stability issues using Firebase Analytics.",
      "Resolved multiple push notification delivery and reliability issues across the application.",
      "Redesigned and rebuilt the app with an updated UI/UX to improve usability and visual consistency.",
      "Migrated the codebase toward a feature-based clean architecture with a clearer and more maintainable folder structure.",
      "Introduced Riverpod for modern state management while working within an existing codebase that used Provider and GetX.",
      "Improved overall app performance, readability, and long-term maintainability through refactoring and architectural cleanup.",
    ],
    graphic: "assets/images/projects/my-uts.png",
    android: "https://play.google.com/store/apps/details?id=com.uts.utstrackingapp",
    apple: "https://apps.apple.com/pk/app/myuts/id1613698217",
    huawei: "https://appgallery.huawei.com/app/C107385877",
    windows: null,
    mac: null,
    web: null,
    company: "USTI",
    showProject: true,
  ),
  ProjectModel(
    title: "EFS Attend",
    description: [
      "EFS Attend is a mobile attendance management application built for field-based and on-site teams.",
      "The app enables team leads to manage their teams by adding users and registering facial data directly within the application.",
      "Attendance is marked using face recognition by capturing a single image, eliminating the need for manual check-ins.",
      "Face recognition is integrated using on-device machine learning to ensure fast and reliable performance.",
      "The application follows an offline-first approach, allowing attendance to be recorded even without an internet connection.",
      "All offline data is securely stored in a local database for up to 45 days and automatically synced when connectivity is restored.",
      "Location-based geofencing ensures attendance can only be marked within approved work areas.",
      "To prevent misuse, the app blocks attendance marking if the device time is not properly synchronized.",
      "The solution is developed in Flutter and supports both Android and iOS platforms.",
    ],
    technologies: ["Flutter", "Provider", "Firebase ML Kit", "TensorFlow", "SQLite", "Firebase"],
    achievements: [
      "Implemented face recognition–based attendance using TensorFlow Lite and ML Kit with approximately 99% accuracy.",
      "Designed and implemented an offline-first architecture with local data retention for up to 45 days.",
      "Built seamless background synchronization to upload stored attendance data once internet access becomes available.",
      "Integrated geofencing to restrict attendance marking to authorized physical locations.",
      "Added device time validation to prevent attendance fraud caused by manual time changes.",
      "Developed complete team management workflows allowing team leads to add users and register facial profiles.",
    ],
    graphic: "assets/images/projects/efs.png",
    android: "https://play.google.com/store/apps/details?id=com.efs.efs_attend.efs_new",
    apple: "https://apps.apple.com/pk/app/efs-attend/id1586428507",
    huawei: null,
    windows: null,
    mac: null,
    web: null,
    company: "CMC M-Tech",
    showProject: true,
  ),

  ProjectModel(
    title: "Pantheon Coffee",
    description: [
      "Pantheon Coffee is a multi-role mobile application developed for a coffee house chain to manage sales, loyalty, and customer engagement.",
      "The app supports three roles: Admin, Barista/Shop Owner, and Customer, each with dedicated features and workflows.",
      "Admins can monitor live sales across all branches through graphical dashboards and manage outlets, users, products, and feedback.",
      "Baristas and shop owners handle daily operations such as adding sales, managing invoices, and interacting with the loyalty system.",
      "Invoices can be created by capturing receipt images, where OCR is used to automatically extract and fill invoice details.",
      "Customers can explore outlets, view menus, track their order history, and engage with the loyalty program.",
      "The app includes a points-based rewards system where users unlock free products based on accumulated points.",
      "All users can manage their profiles, receive push notifications, and close their accounts if needed.",
      "The application allows customers to create accounts independently without staff involvement.",
    ],
    technologies: ["Flutter", "GetX", "Laravel for REST API", "Firebase", "OCR", "REST APIs"],
    achievements: [
      "Designed and implemented a complete multi-role system with clearly separated admin, barista, and customer workflows.",
      "Built real-time sales dashboards for admins to track branch-wise performance using graphical visualizations.",
      "Implemented OCR-based invoice creation by extracting receipt data through image capture to reduce manual data entry.",
      "Developed a loyalty and rewards system enabling point earning, redemption, and product unlocking based on thresholds.",
      "Automated customer account creation during sales when a user does not already exist, with secure first-login password reset flow.",
      "Enabled QR code scanning for free coffee redemptions and loyalty interactions.",
      "Implemented sales, order history, and feedback viewing for both operational staff and customers.",
      "Integrated push notifications across all roles for updates, offers, and system events.",
    ],
    graphic: "assets/images/projects/pantheon.png",
    android: "https://play.google.com/store/apps/details?id=app.mtech.pantheon_cafe",
    apple: "https://apps.apple.com/pk/app/pantheon-coffee/id6737890124",
    huawei: null,
    windows: null,
    mac: null,
    web: null,
    company: "CMC M-Tech",
    showProject: true,
  ),

  ProjectModel(
    title: "Sehat Sahoolat",
    description: [
      "Sehat Sahoolat is a telehealth mobile application designed to connect patients and doctors through secure virtual consultations.",
      "Both patients and doctors can sign up, complete their profiles, and manage appointments using real-time video calling.",
      "Appointments are scheduled based on user time zones to ensure accurate and reliable consultation timing.",
      "During consultations, doctors can add prescriptions and consultation notes that patients can access and download later.",
      "Patients maintain a complete Electronic Medical Record (EMR) by entering personal health data, medical history, and reports.",
      "The EMR includes family history, habits, allergies, medications, medical tests, and key vitals such as heart rate, BMI, and blood group.",
      "Patients can select consultation packages and manage their appointments directly from the app.",
      "Doctors can manage their professional profiles, including expertise, work experience, and supporting documents.",
      "The app supports multi-device management, profile updates, account closure, and secure access across sessions.",
    ],
    technologies: ["Flutter", "GetX", "Agora", "Firebase"],
    achievements: [
      "Implemented real-time video consultations using Agora for reliable doctor–patient communication.",
      "Built a structured EMR system allowing patients to create, manage, and download complete medical records at any time.",
      "Developed timezone-aware appointment scheduling to support users across different regions.",
      "Enabled doctors to add prescriptions and consultation notes during live sessions with persistent patient access.",
      "Implemented bidirectional feedback functionality allowing patients and doctors to review each other.",
      "Created doctor finance management features to track earnings and consultation-related income.",
      "Added role flexibility allowing doctors to switch to patient mode and manage EMRs for themselves and their family members.",
      "Implemented secure device management to control active sessions across multiple devices.",
      "Developed full account management features including profile editing and account closure for all users.",
    ],
    graphic: "assets/images/projects/sehat-sahoolat.png",
    android: "https://play.google.com/store/apps/details?id=com.app.sehat_sahoolat",
    apple: "https://apps.apple.com/pk/app/sehat-sahoolat/id6444405734",
    huawei: null,
    windows: null,
    mac: null,
    web: null,
    company: "CMC M-Tech",
    showProject: true,
  ),
];
